<a href="https://colab.research.google.com/github/Justmin-Lee/ML_Lecture/blob/main/4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [19]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [20]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [21]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [22]:
# Launch the graph in a session
sess = tf.Session()

#Initializes global wariables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                 feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y:y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  66473.08 
Prediction: 
 [-73.01156  -93.303925 -89.16219  -96.98008  -72.46792 ]
10 Cost:  11.564224 
Prediction: 
 [155.03218 180.81126 180.91591 197.1293  136.61787]
20 Cost:  10.898874 
Prediction: 
 [155.70972 181.64919 181.7293  198.01617 137.26196]
30 Cost:  10.8423 
Prediction: 
 [155.69934 181.66023 181.72797 198.01585 137.2753 ]
40 Cost:  10.786026 
Prediction: 
 [155.68695 181.66876 181.72421 198.01288 137.28674]
50 Cost:  10.72995 
Prediction: 
 [155.67458 181.6773  181.72046 198.00989 137.29816]
60 Cost:  10.674339 
Prediction: 
 [155.66223 181.68578 181.71672 198.00691 137.3095 ]
70 Cost:  10.618916 
Prediction: 
 [155.64993 181.69424 181.71298 198.00394 137.32085]
80 Cost:  10.563831 
Prediction: 
 [155.63768 181.7027  181.70927 198.00099 137.33217]
90 Cost:  10.509062 
Prediction: 
 [155.62541 181.71109 181.70554 197.99803 137.34341]
100 Cost:  10.454528 
Prediction: 
 [155.61322 181.71951 181.70184 197.99509 137.35468]
110 Cost:  10.400393 
Prediction: 
 [155.6