<a href="https://colab.research.google.com/github/Justmin-Lee/ML_Lecture/blob/main/4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.set_random_seed(777)   # for Reproducibility

In [6]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]

y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [7]:
# placeholders for a tensor for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
#Launch the graph in a session
sess = tf.Session()

#Initializes global variabels in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ =sess.run(
      [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  76825.016 
Prediction:
 [[ -96.46344 ]
 [-109.819275]
 [-111.79768 ]
 [-119.038536]
 [ -84.00308 ]]
10 Cost:  3.124318 
Prediction:
 [[148.72755]
 [184.87671]
 [178.57411]
 [197.16806]
 [140.77527]]
20 Cost:  2.4178405 
Prediction:
 [[149.47224]
 [185.7665 ]
 [179.45363]
 [198.12483]
 [141.45346]]
30 Cost:  2.4146523 
Prediction:
 [[149.4773 ]
 [185.76732]
 [179.45723]
 [198.12775]
 [141.45361]]
40 Cost:  2.4114785 
Prediction:
 [[149.48013]
 [185.76547]
 [179.45819]
 [198.1278 ]
 [141.45174]]
50 Cost:  2.4083202 
Prediction:
 [[149.48293]
 [185.76361]
 [179.45914]
 [198.12782]
 [141.44984]]
60 Cost:  2.4051623 
Prediction:
 [[149.48573]
 [185.76175]
 [179.46008]
 [198.12785]
 [141.44797]]
70 Cost:  2.4020295 
Prediction:
 [[149.48854]
 [185.75992]
 [179.46103]
 [198.1279 ]
 [141.4461 ]]
80 Cost:  2.3989038 
Prediction:
 [[149.49133]
 [185.75807]
 [179.46198]
 [198.12793]
 [141.44423]]
90 Cost:  2.395796 
Prediction:
 [[149.4941 ]
 [185.75623]
 [179.46289]
 [198.12793]
 [141.4