<a href="https://colab.research.google.com/github/Justmin-Lee/ML_Lecture/blob/main/4_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
tf.set_random_seed(777)  # for reproducibility

In [3]:
# load file on my desktop
from google.colab import files
myfile = files.upload()

Saving data-01-test-score.csv to data-01-test-score.csv


In [9]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [10]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape: ", x_data.shape)
print(y_data, "\ny_data shape: ", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape:  (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape:  (25, 1)


In [12]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [13]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [15]:
# Launch the graph in a session
sess = tf.Session()

# Initializes global variables in th graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                 feed_dict={X: x_data, Y: y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [173.58476]
 [173.19955]
 [165.64278]
 [156.87561]
 [192.32863]]
160 Cost:  17.202673 
Prediction:
 [[154.33728]
 [185.21562]
 [182.78679]
 [198.64517]
 [141.29272]
 [103.00073]
 [147.7702 ]
 [108.37877]
 [172.26244]
 [158.26694]
 [142.71352]
 [140.27492]
 [189.411  ]
 [157.98131]
 [148.31992]
 [187.51398]
 [150.88075]
 [177.35336]
 [180.68579]
 [161.51122]
 [173.59348]
 [173.2069 ]
 [165.64796]
 [156.84926]
 [192.32431]]
170 Cost:  17.114317 
Prediction:
 [[154.32806]
 [185.21664]
 [182.78094]
 [198.64609]
 [141.29048]
 [103.01175]
 [147.77834]
 [108.39487]
 [172.2751 ]
 [158.29585]
 [142.71748]
 [140.28696]
 [189.39769]
 [157.96063]
 [148.3307 ]
 [187.52084]
 [150.85596]
 [177.36494]
 [180.67007]
 [161.49718]
 [173.60216]
 [173.21417]
 [165.65314]
 [156.82301]
 [192.32   ]]
180 Cost:  17.026712 
Prediction:
 [[154.31888 ]
 [185.21764 ]
 [182.77512 ]
 [198.64703 ]
 [141.28825 ]
 [103.022705]
 [147.78647 ]
 [108.4109  ]
 [172.28769 ]
 [158.32465 ]
 

In [17]:
# Ask my score
print("Your score will be ", sess.run(hypothesis,
                                      feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[185.64378]]
Other scores will be  [[168.36519]
 [179.66455]]
